### ISSUE TITLE
In domain listing/testing, if it doesn't exist, there is a key error

### ISSUE THREAD

**Issue by maxpearl** [OpenTechFund/bypass-otf_proxy#19]
```
Listing and Testing severreal.org...
Traceback (most recent call last):
  File "automation.py", line 284, in <module>
    automation()
  File "/home/max/.local/share/virtualenvs/bypass-otf_proxy-fBr8tRtQ/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/max/.local/share/virtualenvs/bypass-otf_proxy-fBr8tRtQ/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/max/.local/share/virtualenvs/bypass-otf_proxy-fBr8tRtQ/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/max/.local/share/virtualenvs/bypass-otf_proxy-fBr8tRtQ/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "automation.py", line 53, in automation
    domain_data = mirror_detail(domain=domain, proxy=proxy, mode=mode)
  File "/home/max/Code/myprojects/bypass-otf_proxy/bcapp/flaskapp/mirror_tests.py", line 99, in mirror_detail
    exists = domain_data['exists']
KeyError: 'exists'

```

**Comment by maxpearl** [comment]
Fixed. https://github.com/OpenTechFund/bypass-otf_proxy/commit/cc7e7bcce9b758cca945f3077044267e0cc73ff3
